// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gb28181_config.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcGb28181Config {
  public static partial class Gb28181Config
  {
    static readonly string __ServiceName = "GrpcGb28181Config.Gb28181Config";

    static readonly grpc::Marshaller<global::GrpcGb28181Config.GbConfigRequest> __Marshaller_GbConfigRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcGb28181Config.GbConfigRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcGb28181Config.GbConfigReply> __Marshaller_GbConfigReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcGb28181Config.GbConfigReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcGb28181Config.GbConfigRequest, global::GrpcGb28181Config.GbConfigReply> __Method_GbConfig = new grpc::Method<global::GrpcGb28181Config.GbConfigRequest, global::GrpcGb28181Config.GbConfigReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GbConfig",
        __Marshaller_GbConfigRequest,
        __Marshaller_GbConfigReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcGb28181Config.Gb28181ConfigReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Gb28181Config</summary>
    public abstract partial class Gb28181ConfigBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::GrpcGb28181Config.GbConfigReply> GbConfig(global::GrpcGb28181Config.GbConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Gb28181Config</summary>
    public partial class Gb28181ConfigClient : grpc::ClientBase<Gb28181ConfigClient>
    {
      /// <summary>Creates a new client for Gb28181Config</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public Gb28181ConfigClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Gb28181Config that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public Gb28181ConfigClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected Gb28181ConfigClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected Gb28181ConfigClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GrpcGb28181Config.GbConfigReply GbConfig(global::GrpcGb28181Config.GbConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GbConfig(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GrpcGb28181Config.GbConfigReply GbConfig(global::GrpcGb28181Config.GbConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GbConfig, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GrpcGb28181Config.GbConfigReply> GbConfigAsync(global::GrpcGb28181Config.GbConfigRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GbConfigAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GrpcGb28181Config.GbConfigReply> GbConfigAsync(global::GrpcGb28181Config.GbConfigRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GbConfig, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override Gb28181ConfigClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new Gb28181ConfigClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(Gb28181ConfigBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GbConfig, serviceImpl.GbConfig).Build();
    }

  }
}
#endregion
